### ISSUE TITLE
Bug on Startup

### ISSUE THREAD

**Issue by DrGrimme** [SE2-Gruppe2-SS23/Mankomania#64]
on Startup Start Screen opens/reopens multiple times if "Start" is clicked to Early, App Crashes

**Comment by DrGrimme** [comment]
W/Parcel: Expecting binder but got null!
W/ViewLayoutInspector: java.lang.IllegalArgumentException: Surface isn't valid, source.isValid() == false
        at android.view.PixelCopy.request(PixelCopy.java:181)
        at com.android.tools.agent.appinspection.framework.SynchronousPixelCopy.request(SynchronousPixelCopy.java:64)
        at com.android.tools.agent.appinspection.framework.ViewExtensionsKt.takeScreenshot(ViewExtensions.kt:80)
        at com.android.tools.agent.appinspection.ViewLayoutInspector$registerScreenshotCallback$doCapture$1$1.run(ViewLayoutInspector.kt:436)
        at com.android.tools.agent.appinspection.ViewLayoutInspector.executeCapture(ViewLayoutInspector.kt:513)
        at com.android.tools.agent.appinspection.ViewLayoutInspector.access$executeCapture(ViewLayoutInspector.kt:103)
        at com.android.tools.agent.appinspection.ViewLayoutInspector$startCapturing$captureExecutor$1$1.run(ViewLayoutInspector.kt:325)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
